### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by khrichtchatyi** [Pixate/Titanium-PixateFreestyle#11]
What about pre-build version?

My log file:

Build settings from command line:
    SDKROOT = iphoneos7.0

=== BUILD TARGET PixateFramework OF PROJECT PixateFramework WITH CONFIGURATION Release ===

Check dependencies

CompileC build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.o Classes/ComPixateFrameworkModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Frameworks/Python.framework/Versions/3.3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wno-parentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DTI_VERSION= -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -miphoneos-version-min=4.0 -iquote /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-generated-files.hmap -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-own-target-headers.hmap -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-all-target-headers.hmap -iquote /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-project-headers.hmap -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/Release-iphoneos/include -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/3.1.3.GA/iphone/include -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/3.1.3.GA/iphone/include/TiCore -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/DerivedSources/armv7 -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/DerivedSources -F/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/Release-iphoneos -F/Users/pixate/Desktop/Pixate/Framework -F/Users/pixate/Documents/Titanium_Studio_Workspace/PixateFramework/platform/iphone -F/Users/pixate/Desktop -DTI_POST_1_2 -include /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.DeveloperTools/5.0.1-5A2053/Xcode/SharedPrecompiledHeaders/ComPixateFramework_Prefix-cnzdjkmqoeksnrevbqybnfimsplp/ComPixateFramework_Prefix.pch -MMD -MT dependencies -MF /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.d --serialize-diagnostics /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.dia -c /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/Classes/ComPixateFrameworkModule.m -o /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.o
In file included from /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/Classes/ComPixateFrameworkModule.m:19:
/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/Classes/ComPixateFrameworkModule.h:19:9: fatal error: 
      'TiModule.h' file not found
# import "TiModule.h"

```
    ^
```

1 error generated.

CompileC build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.o Classes/ComPixateFrameworkModule.m normal armv7s objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Frameworks/Python.framework/Versions/3.3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7s -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wno-parentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DTI_VERSION= -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -miphoneos-version-min=4.0 -iquote /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-generated-files.hmap -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-own-target-headers.hmap -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-all-target-headers.hmap -iquote /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/ComPixateFramework-project-headers.hmap -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/Release-iphoneos/include -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/3.1.3.GA/iphone/include -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/3.1.3.GA/iphone/include/TiCore -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/DerivedSources/armv7s -I/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/DerivedSources -F/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/Release-iphoneos -F/Users/pixate/Desktop/Pixate/Framework -F/Users/pixate/Documents/Titanium_Studio_Workspace/PixateFramework/platform/iphone -F/Users/pixate/Desktop -DTI_POST_1_2 -include /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.DeveloperTools/5.0.1-5A2053/Xcode/SharedPrecompiledHeaders/ComPixateFramework_Prefix-dxbefdhcqxtdzxghhbelphbvuduh/ComPixateFramework_Prefix.pch -MMD -MT dependencies -MF /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.d --serialize-diagnostics /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.dia -c /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/Classes/ComPixateFrameworkModule.m -o /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.o
In file included from /Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/Classes/ComPixateFrameworkModule.m:19:
/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/Classes/ComPixateFrameworkModule.h:19:9: fatal error: 
      'TiModule.h' file not found
# import "TiModule.h"

```
    ^
```

1 error generated.

2013-11-09 16:44:54.632 xcodebuild[85104:3e03]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3574/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
Details:  Failed to load dependencies output contents from `/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “ComPixateFrameworkModule.d” couldn’t be opened because there is no such file." UserInfo=0x7f9ffb2d7c90 {NSFilePath=/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.d, NSUnderlyingError=0x7f9ffb2d9f90 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, F) [F = <lambda at /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3574/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:168:73>]
Thread:   <NSThread: 0x7f9ff8d6f160>{name = (null), num = 8}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2013-11-09 16:44:54.632 xcodebuild[85104:f03]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3574/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
Details:  Failed to load dependencies output contents from`/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “ComPixateFrameworkModule.d” couldn’t be opened because there is no such file." UserInfo=0x7f9ffb2db7a0 {NSFilePath=/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.d, NSUnderlyingError=0x7f9ffb2d3940 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/63ek/Documents/SDKs/modules/pixate/Titanium-Pixate/Pixate/build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString ___strong, F) [F = <lambda at /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3574/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:168:73>]
Thread:   <NSThread: 0x7f9ffb2d41e0>{name = (null), num = 7}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
*_ BUILD FAILED **

The following build commands failed:
    CompileC build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7/ComPixateFrameworkModule.o Classes/ComPixateFrameworkModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/PixateFramework.build/Release-iphoneos/PixateFramework.build/Objects-normal/armv7s/ComPixateFrameworkModule.o Classes/ComPixateFrameworkModule.m normal armv7s objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
xcodebuild failed

**Comment by thelonious** [comment]
Maxim,

We're now using GitHub's "releases" mechanism. You can find that here:

https://github.com/Pixate/Titanium-Pixate/releases/tag/2.0.0

I'll look into the build error. In the meantime, you may need to open up the Xcode project and verify that it is pointing to the Pixate.framework file. You can try building in Xcode to verify. If it doesn't build, then remove and re-add the copy of Pixate.framework that you are using.

**Comment by khrichtchatyi** [comment]
many thanks
