### ISSUE TITLE
Building the module failing with the new version

### ISSUE THREAD

**Issue by robertscherer** [Pixate/Titanium-PixateFreestyle#12]
I have installed the latest Pixate Freestyle Framework for iOS, it is present in my user Document Folder.

After following the Build Instructions, I get the following error:

```
The following build commands failed:
    CompileC build/PixateFreestyle.build/Release-    iphoneos/PixateFreestyle.build/Objects-normal/armv7/ComPixateFreestyleModule.o Classes/ComPixateFreestyleModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/PixateFreestyle.build/Release-iphoneos/PixateFreestyle.build/Objects-normal/armv7s/ComPixateFreestyleModule.o Classes/ComPixateFreestyleModule.m normal armv7s objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

The symbolic link to the PixateFreestyle.framework folder works and links to the correct place, the titanium.xconfig `$TITANIUM_SDK` variable is correct.

**Comment by pcolton** [comment]
Can you use the binary at this time?

https://github.com/Pixate/Titanium-PixateFreestyle/releases

**Comment by robertscherer** [comment]
I can for now.

**Comment by pcolton** [comment]
I found the issue. Was a schemes issue and framework search path issue. You should be able to pull again now and build. You might need to delete back schemes in Xcode by opening up the PixateFreestyle.xcodeproj and removing the 2 unshared schemes (the good ones should be shared).
