### ISSUE TITLE
Loading the Pixate module with require() doesn't work anymore

### ISSUE THREAD

**Issue by robertscherer** [Pixate/Titanium-PixateFreestyle#14]
In my Pixate-powered Titanium applications i use the live CSS refresh functionality by using the following piece of code in my app.js:

```
if(Titanium.Platform.model.indexOf('Simulator') > -1) {
    var PX = require('com.pixate.pixatefreestyle'); // changed to new module name
    PX.styleSheetFromFilePathWithOrigin({ 
        monitor: true,
        origin: 0,
        filename: '/path/to/my.css'
    });
}
```

In the new version i get the following error:

```
[ERROR] Script Error Couldn't find module: com.pixate.pixatefreestyle
```

When I use the old module name `com.pixate.framework`, the app crashes quietly after start.

**Comment by pcolton** [comment]
I'm able to reproduce, but not able to figure out why it can't find it. Will keep checking.

**Comment by pcolton** [comment]
I found a mismatched id and guid. I've updated the release download, could you give it a try?

https://github.com/Pixate/Titanium-PixateFreestyle/releases/tag/v2.1.0

**Comment by pcolton** [comment]
Ok, finally got it working. Seems to be an odd bug with Titanium. I had to rename the module name to com.pixate.freestyle. Now it seems to work.

https://github.com/Pixate/Titanium-PixateFreestyle/releases/tag/v2.1.0

**Comment by robertscherer** [comment]
I can confirm this works fine for me.
