### ISSUE TITLE
Label positioning doesn't work

### ISSUE THREAD

**Issue by robertscherer** [Pixate/Titanium-PixateFreestyle#16]
With Titanium SDK 3.2.2GA and Titanium-Pixate 2.1.1, when adding a styleClass to a Label, it disappears.

This used to work with Titanium SDK 3.1.3GA and Pixate 2.1.0, it has the same broken behavior with Titanium SDK >= 3.2.x and any Pixate version.

app.js

```
var win1 = Titanium.UI.createWindow({  
    backgroundColor:'#fff'
});
win1.open();

var normalLabel = Ti.UI.createLabel({
    text: 'Label Text - Works',
    top: 10,
    left: 10
});
win1.add(normalLabel);

var pixateLabel = Ti.UI.createLabel({
    text: 'Label Text - Doesnt show',
    styleClass: 'test-label'
});
win1.add(pixateLabel);
```

default.css

```
.test-label {
    top: 20px;
    left: 20px;
}
```

Please find the ready-to-test demo app here: http://www.codekanzlei.de/tmp/pixate-label-test.zip

This isn't the first time I have had problems with styling and positioning labels - other controls work fine and as expected.

**Comment by pcolton** [comment]
We've implemented a fix we need you to test. I can send you a test .zip if you send me your email (send it to paul at pixate.com). Also, I noticed your sample project didn't have the PXTitanium option set, see https://github.com/Pixate/Titanium-PixateFreestyle#adding-the-pixatefreestyle-runtime-properties

By the way, now that the code is open sourced, we offer premium support when there is urgency. I took care of it this time. Please see: http://www.pixate.com/support.html

**Comment by robertscherer** [comment]
I have updated the test application to the new 2.1.2 release. The label shows now, but the positioning doesn't work yet.

Please find the updated test app here: http://www.codekanzlei.de/tmp/pixate-label-test-2.zip

![ios simulator screen shot 18 03 2014 08 10 06](https://f.cloud.github.com/assets/593203/2445188/7b2406aa-ae6c-11e3-9b24-943c249ab1e5.png)

**Comment by pcolton** [comment]
This has been fixed in the next build.

**Comment by robertscherer** [comment]
I can confirm this is fixed, thank you!
