### ISSUE TITLE
Compiled OK - but no ZIP file?

### ISSUE THREAD

**Issue by de1mat** [Pixate/Titanium-PixateFreestyle#2]
I managed to build OK - the end result was "*\* BUILD SUCCEEDED **"

But I cannot see any ZIP file anywhere?

Not sure how to proceed to use this with Titanium. I was a Pixate Kickstarter backer so keen to get this working. Any help appreciated.

Matt

**Comment by de1mat** [comment]
In the docs it says "If you'd like to build the module yourself, this is the simple process."

This implies that I may not need to build it myself? Do you have a precompiled version of this module somewhere that I can use?

**Comment by yuchi** [comment]
That's easier than it looks. (I had problems with Pixate 1.1b3, but Pixate 1.0.3 works pretty well)
1. Link Pixate.framework, you can [download it from the site](http://www.pixate.com) with:
   
   ```
   cd PATH_TO_THIS_REPO
   ln -s PATH_TO_UNZIPPED_PIXATE/Framework/PXEngine.framework PXEngine.framework
   ```
2. run `./rebuild.sh`

The zip file is in fact in the root itself of the project in the form `com.pixate.pxengine-iphone-MODULE_VERSION.zip`.

**Comment by thelonious** [comment]
@Mobilizr We now include the latest module in the top-level "bin" directory in this repo

**Comment by de1mat** [comment]
Indeed - thank you, that is much better.
