### ISSUE TITLE
Error on Build (ios7, xcode5)

### ISSUE THREAD

**Issue by Gerhard-Kanzler** [Pixate/Titanium-PixateFreestyle#3]
The error i get:

Undefined symbols for architecture i386:
  "_CTFontManagerRegisterGraphicsFont", referenced from:
      +[PX_AO loadFontFromURL:] in PXEngine(obj51.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation

Is it posible to resolve this problem by the Module self?
http://answers.pixate.com/questions/145/problem-with-the-titanium-module.html

**Comment by anosognosia** [comment]
Sounds like you need to add the "CoreText" framework to your Xcode project, as outlined in:
 https://wiki.appcelerator.org/display/guides/iOS+Module+Development+Guide#iOSModuleDevelopmentGuide-AddingSpecialCompilerDirectives

**Comment by Gerhard-Kanzler** [comment]
I have resolved this by updating to the newest release of Titanium SDK.

**Comment by elkraneo** [comment]
thx anosognosia, adding core text worked for me in a project without Titanium and with the same compiling error.

**Comment by awais64** [comment]
you should add some frameworks

**Comment by awais64** [comment]
you should add these frameworks : "CoreText.framework" , "CoreMotion.framework" and "ALAssetsLibrary.framework" into the "Targets"==>"Build Phases"==>"Link Binary with Libraries"
and try to rebuild.
