### ISSUE TITLE
Couldn't find module "com.pixate.pxengine"

### ISSUE THREAD

**Issue by robertscherer** [Pixate/Titanium-PixateFreestyle#6]
After updating to 2.0.0RC1 and compiling the application, Pixate works as expected. 

However, when trying to use the module in code via "var PX = require('com.pixate.pxengine');", the app crashes with a red Titanium error screen saying that the com.pixate.pxengine could not be found.

Rolling back to 1.1.0b4 fixed the issue.

**Comment by thelonious** [comment]
Robert,

What version of Titanium are you using? If you feel up to it, you can build your own module to see if that resolves the issue for you. Instruction are here, towards the bottom of the page: http://pixate.github.io/Titanium-Pixate/

**Comment by robertscherer** [comment]
Hi,

I'm using 3.1.3.GA. I have built the module myself, but I have still the same error. 

Please find the build output here: https://gist.github.com/robertscherer/6852107

Also, find a plain sample application which causes the error too, here: http://www.robertscherer.de/trash/PixateTest.zip

**Comment by thelonious** [comment]
Robert,

Thanks for all of the info. The last Titanium version we tested with was 3.1.2.GA, so I suspect something has broken in 3.1.3.GA. We'll take a look and let you know what we find out.

**Comment by thelonious** [comment]
Robert,

We pushed an update for 2.0RC3. Please give that a try to see if that resolves your issue. Please note that the module id has changed to "com.pixate.framework".

Thanks,
Kevin

**Comment by robertscherer** [comment]
Hi Kevin,

the update fixed the issue, thanks!

Robert
