### ISSUE TITLE
Building the module fails because of SDK location variable

### ISSUE THREAD

**Issue by robertscherer** [Pixate/Titanium-PixateFreestyle#7]
When trying to build the module by the build instructions, I stumbled upon the following issue:

```
$ ./build.py 
Traceback (most recent call last):
  File "./build.py", line 236, in <module>
    build_module(manifest,config)
  File "./build.py", line 181, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools
```

The reason for the issue is in titanium.xcconfig:

```
TITANIUM_SDK = /Library/Application Support/Titanium/mobilesdk/osx/$(TITANIUM_SDK_VERSION)
```

I have the SDK installed in my user folder. By prepending $HOME to the path, the problem is fixed.

```
TITANIUM_SDK = $HOME/Library/Application Support/Titanium/mobilesdk/osx/$(TITANIUM_SDK_VERSION)
```

This should either be automatically detected or maybe included in the build instructions.

**Comment by thelonious** [comment]
Hi robertscherer,

We added a comment to the build section talking about how that path can be updated in the titanium.xcconfig file.

Thanks,
Kevin
