### ISSUE TITLE
[ERROR] :  Module com.pixate.pxengine version 2.0.0RC3 is missing library file libcom.pixate.pxengine.a

### ISSUE THREAD

**Issue by khrichtchatyi** [Pixate/Titanium-PixateFreestyle#8]
libcom.pixate.framework.a rename to libcom.pixate.pxengine.a

**Comment by thelonious** [comment]
63ek,

I'm not sure what you are reporting here, but we did rename the module to "com.pixate.framework". This is turn renames the .a file it generates. It sounds like you are trying to use the new .a file in an older module? The current build updates the module name and GUID, so I would recommend using that, if possible

**Comment by khrichtchatyi** [comment]
I use Titanium-Pixate / bin / com.pixate.framework-iphone-2.0.0RC3.zip
When try to run precompiled module, you'll be have the error

**Comment by thelonious** [comment]
63ek,

Hmm, I'm unable to recreate that here. I created a new project using the module from this repository and all is working fine. You may need to clean your project: Project->Clean...

**Comment by nuno** [comment]
I can confirm works fine here in my setup.

**Comment by khrichtchatyi** [comment]
com.pixate.framework-iphone-2.0.0RC3.zip after unzip

![1fix](https://f.cloud.github.com/assets/1884450/1448785/73e3ea30-425c-11e3-81a6-dff3c12ad902.png)

[ERROR] :  Module com.pixate.pxengine version 2.0.0RC3 is missing library file: /modules/iphone/com.pixate.pxengine/2.0.0RC3/libcom.pixate.pxengine.a

**Comment by thelonious** [comment]
63ek,

That is the correct name for the RC3 release of the Titanium module. It really sounds like you have a mixture of old and new modules. I suggest you remove any copies of the module you have (user and system level), clean your project, then install the module.

**Comment by khrichtchatyi** [comment]
Sorry. But afterall I realized where I was wrong. It's my error.
