### ISSUE TITLE
Where I should set that  "monitor" arg to edit-live css?

### ISSUE THREAD

**Issue by nuno** [Pixate/Titanium-PixateFreestyle#9]
Hi, is not a real issue, is more a question.

I've look at code and I saw "monitor" arg, where I should set that arg?

I'm using alloy and css work just fine, but will'b nice live-edit, assuming that I want access to the object, like:

``` javascript
var PX = require('com.pixate.framework');
console.log(JSON.stringify(PX));
```

Thank you!

**Comment by thelonious** [comment]
Nuno,

When you load a css file vis "styleSheetFromFilePathWithOrigin", you can pass in the monitor flag there. For example:

``` javascript
var PX = require('com.pixate.framework');
PX.styleSheetFromFilePathWithOrigin({
    filename: '/Users/nuno/Desktop/user.css',
    origin: PX.PXStylesheetOriginUser,
    monitor: true,
});
```

HTH,
Kevin

**Comment by nuno** [comment]
Kevin, thank you for this info, I was passing just monitor: true  and not filename and origin :) 

Thank you again
- Nuno Costa

P.S you can close if you d'like.

**Comment by thelonious** [comment]
Great! Thanks Nuno.
